language: node_js
node_js:
  - "5"
services:
  - postgresql
before_script:
  - psql -c 'create database tk;' -U postgres
  - psql -c 'ALTER USER Postgres WITH PASSWORD \'root\';' -U postgres
addons:
  hosts:
    - postgres
notifications:
  email: false
