language: node_js
node_js:
  - "5"
services:
  - postgresql
before_install:
  - psql -c 'create database tk;' -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'root';" -U postgres
  - if [ -d /home/travis/.nvm/versions/node/v5.11.0/lib/strongloop/bin ]; then echo "strongloop already installed"; else npm i -g strongloop bower; fi;
  - npm install
addons:
  hosts:
    - postgres
notifications:
  email: false
cache:
  directories:
    - /home/travis/.nvm/versions/node/v5.11.0/lib/bower@1.7.9
    - /home/travis/.nvm/versions/node/v5.11.0/lib/strongloop@6.0.0
